/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package volt;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  void stringCleaner() {
    // Test that all period are removed
    String noPeriods = App.stringCleaner("This is. a test.");
    assertTrue(!noPeriods.contains("."));

    // Test that we do keep periods for package names
    System.out.println("Running Tests");
    String packages = App.stringCleaner("Android package Phone.Robot.java has a vulnerability.");
    System.out.println(packages);
    assertTrue(packages.contains("phone.robot.java"));
    assertTrue(!packages.contains("vulnerability."));
    String sample = "Race condition in the Intel(R) .. (dot dot) Driver and Support for Apple(TM): \"Assistant\" before version 20.1.5 may allow an authenticated user to potentially enable denial of service (dos) via local access.";
    var cleanString = App.stringCleaner(sample);
    assertTrue(
        !cleanString.contains("(tm)") || !cleanString.contains(".") || !App.stringCleaner(sample).contains("(r)"));
    System.out.println(App.stringCleaner(sample));
  }
}
